services:
  postgres:
    image: quay.io/debezium/postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_DB=events
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:Z
    command: ["postgres", "-c", "wal_level=logical"]

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.1
    container_name: redpanda
    command: >
      redpanda start
      --smp 1
      --overprovisioned
      --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092" # Port for Quarkus (External)

  debezium:
    image: quay.io/debezium/connect:2.7
    container_name: debezium
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=redpanda:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
    depends_on:
      - redpanda
      - postgres
